# *MATH&STAT-2. Линейная алгебра. Часть 2
## Юнит 3. Введение в машинное обучение 
### Skillfactory: DSPR-19

### 2.2. Неоднородные СЛАУ

### 2.3. Случай «Идеальная пара»

### Задание 2.3.1
Запишите систему уравнений, если ее расширенная матрица имеет вид  

Ответ:  
4w1+7w2-w3=7  
2w1+w2+w3=2  
-4w1+2w2+5w3=3  



### Задание 2.3.2
Продолжите предложение, выбрав верное утверждение. 

Системы уравнений имеют одинаковые решения, потому что их расширенные матрицы пропорциональны

### Задание 2.3.3
Запишите расширенную матрицу системы A|b

In [1]:
import numpy as np

A = np.array([[4,7,20],
            [5,10,30]])
A

array([[ 4,  7, 20],
       [ 5, 10, 30]])

### 2.4. Случай «В активном поиске»

### Задание 2.3.4

Решите систему линейных уравнений


4x + 7y = 20  
5x + 10y = 30  

10y = 30 - 5x  
y = (30 - 5x)x 0.1 = 3 - 0.5x  

4x + 7(3 - 0.5x) = 20  
4x + 21 - 3.5x = 20  
4x - 3.5x = -1  
0.5x = -1  
**x = -2**

y = 3 - 0.5x  
y = 3 - (-2 x 0.5)  
**y = 4**

### Задание 2.4.1
Сколько решений имеет система уравнений  
Ответ: Бесконечно много, так как в ней 2 непротиворечивых уравнения на 3 неизвестных

### Задание 2.4.2
Сколько решений имеет система уравнений  
Ответ: Бесконечно много верно

### Задание 2.4.3
Система линейных алгебраических уравнений НЕ может иметь  
Ответ: Ровно 5 решений

### Задание 2.4.4
В каком/каких из следующих случаев система будет иметь бесконечно много решений?  
Ответ: 
 - 4 неизвестных, 3 уравнения, rk(A) = 2, rk(A|b) = 2
 - 4 неизвестных, 3 уравнения, rk(A) = 3, rk(A|b) = 3

### 2.5 Случай «Всё сложно» ч.1

### Задание 2.5.1
Какие ситуации в СЛАУ невозможны?
 - 8 неизвестных, 12 уравнений, rk(A) = 10, rk(A|b) =  10
 - 8 неизвестных, 12 уравнений, rk(A) = 2, rk(A|b) =  1



### Задание 2.5.2
В переопределенной системе Aw = b обязательно

Ответ:
- Ранг расширенной матрицы больше ранга A
- Нет точных решений
- Столбец свободных коэффициентов независим со столбцами матрицы A

### Задание 2.5.3

Согласно OLS, из нескольких приближённых решений переопределенной СЛАУ лучше то

Ответ: У которого вектор ошибок имеет меньшую длину

### Задание 2.6.1
Вычислите вектор ошибок для приближённого решения системы w, если

In [7]:
import numpy as np

A = np.array([[1 , -5],[2 , 1],[1 , 1]])
print("Матрица A")
print(A)
print(" ")

b = np.array([1, 2, 2])
b = np.reshape(b,(len(b),1))
print("вектор b")
print(b)
print(" ")

w = np.array([1, 1])
w = np.reshape(w,(len(w),1))
print("вектор w")
print(w)
print(" ")

temp = b-A@w
temp

Матрица A
[[ 1 -5]
 [ 2  1]
 [ 1  1]]
 
вектор b
[[1]
 [2]
 [2]]
 
вектор w
[[1]
 [1]]
 


array([[ 5],
       [-1],
       [ 0]])

### Задание 2.6.2
В OLS оценке коэффициентов переопределенной СЛАУ

Ответ:
- Вектор ошибок ортогонален столбцам А
- Вектор ошибок имеет минимальную длину из всех возможных
- Вектор ошибок e = b-A*w  

### Задание 2.6.3
Найдите OLS оценку для коэффициентов w1, w2 СЛАУ

In [8]:
A = np.array([[1 , 2],[-3 , 1],[1 , 2],[1, -1]])
print("Матрица A")
print(A)
print(" ")

b = np.array([1, 4, 5, 0])
b = np.reshape(b,(4,1))
print("вектор b")
print(b)

Матрица A
[[ 1  2]
 [-3  1]
 [ 1  2]
 [ 1 -1]]
 
вектор b
[[1]
 [4]
 [5]
 [0]]


### Задание 2.6.3_1
a) Вычислите матрицу Грама столбцов А: A_T*A

In [12]:
temp = A.T @ A

print(f"матрица Грама")
print(temp)

матрица Грама
[[12  0]
 [ 0 10]]


### Задание 2.6.3_2
(A_T*A)-1 имеет вид:

Ответ:
diag (1/12, 1/10)

### Задание 2.6.3_3
A.T@b = ?

In [10]:
temp = A.T @ b
temp

array([[-6],
       [16]])

### Задание 2.6.3_4
w_ = ?  
***Примечание: для корректого ответа НЕ округляйте (A.T@A)^-1***  
Введите координаты полученного вектора через запятую (без пробела):

In [13]:
G_inv = np.linalg.inv(A.T @ A)
temp = G_inv @ (A.T @ b)
temp

array([[-0.5],
       [ 1.6]])

### Задание 2.6.3_5
e) Вид матрицы Грама в данной конкретной задаче говорит  

***Ответ:***
- Об ортогональности столбцов матрицы А
- О линейной независимости столбцов матрицы А

### 2.7. Классическая OLS линейная регрессия

### Задание 2.7.1

В постановке задачи линейной регрессии запись
y, x1, x2, ... x8 R117
означает, что

Ответ: 
в модели 8 факторов и 117 наблюдений 

### Задание 2.7.2

Продолжите утверждение:

Система уравнений для поиска коэффициентов линейной регрессии

Ответ:

- Как правило, переопределенная
- Как правило, «высокая» (строк >> столбцов)

### Задание 2.7.3

В системе y = Aw для поиска коэффициентов линейной регрессии:

Ответ:
- w — вектор неизвестных коэффициентов
- А — матрица значений признаков, записанных в столбцы

### Задание 2.7.4

В задаче прогнозирования PRICE = w0 + w1*CRIM + w2*RM

Ответ:
- PRICE — целевая переменная
- Есть intercept

### Задание 2.7.5
Используя данные, полученные нами в модуле ранее (см. таблицу и результат применения OLS к ней) сделайте прогноз типичной стоимости (в тыс. долларов) дома в городке с уровнем преступности CRIM==0.2 и средним количеством комнат в доме RM==6.  
Ответ округлите до тысячных

In [14]:
w = np.array([-29.3, -0.26, 8.4])
w = np.reshape(w,(len(w),1))
print("вектор w\n", w)

CRIM = 0.2
RM = 6
x = np.array([1, CRIM, RM])

temp = (x@w)[0]
print(round(temp,3))

вектор w
 [[-29.3 ]
 [ -0.26]
 [  8.4 ]]
21.048


In [15]:
y = -29.3-0.26*0.2+8.4*6
print(round(y, 3))

21.048


### 2.8. Проблемы в классической OLS модели

### Задание 2.8.1
Классическая OLS оценка коэффициентов линейной регрессии не получится, если 

Ответ:  
- В модели 3 признака и один является суммой двух других
- В модели 2 признака пропорциональны

### Задание 2.8.2
Можно ли найти классическую OLS оценку в модели целевой переменной y и регрессорами x1, x2, x3

In [16]:
y = np.array([ 1, 2, 1, 2])
y = np.reshape(y,(len(y),1))
print("вектор y\n", y)
print(" ")

x1 = np.array([ 1, 1, 0, 2])
x1 = np.reshape(x1,(len(x1),1))
print("вектор x1\n", x1)
print(" ")

x2 = np.array([ -1, 1, 0, 0])
x2 = np.reshape(x2,(len(x2),1))
print("вектор x2\n", x2)
print(" ")

x3 = np.array([ 0, 2, 0, 2])
x3 = np.reshape(x3,(len(x3),1))
print("вектор x3\n", x3)

вектор y
 [[1]
 [2]
 [1]
 [2]]
 
вектор x1
 [[1]
 [1]
 [0]
 [2]]
 
вектор x2
 [[-1]
 [ 1]
 [ 0]
 [ 0]]
 
вектор x3
 [[0]
 [2]
 [0]
 [2]]


In [17]:
A=np.concatenate((x1, x2, x3), axis=1)

temp = np.linalg.det(A.T@A)
temp

0.0

Матрица Грамма вырождена. Ответ: НЕТ

### 2.9. Стандартизация признаков



### Задание 2.9.1
Стандартизация поможет улучшить обусловленность модели, если

Ответ:   
y = 1, 2, 1, 2   
x1 = 0.1, 0.01, 0, 0.02   
x2 = -1000, 1000, 8000, 7000

### Задание 2.9.2
Стандартизируйте признак  
$x = {11 \choose 8}$

In [19]:
x = np.array([11,8])
x_center = x - np.mean([x])

temp = x_center/(np.dot(x_center,x_center)**0.5)


print(f"Стандартизированный признак x\n", round(temp[0],2), round(temp[1],2))

Стандартизированный признак x
 0.71 -0.71


### 2.10. Корреляционная матрица  

### Задание 2.10.1
Если корреляция между факторами x1 и x2 равна -0.81, это значит:  

Ответ:  
Чем больше x2, тем меньше x1

### Задание 2.10.2
Найдите все НЕверные утверждения.  

Ответ:  
- Корреляционная матрица всегда невырождена 
- Если ранг корреляционной матрицы максимален, то мультиколлинеарности нет 