# MATH&STAT-1. Линейная алгебра. Часть 1 
## Юнит 3. Введение в машинное обучение 
### Skillfactory: DSPR-19

### 1.2. Векторы. Основные понятия

In [1]:
import numpy as np
s = np.array([33,65,50,45])
print(s)
print(f"размерность {len(s)}")
print(f"третий элемент массива {s[2]}")

[33 65 50 45]
размерность 4
третий элемент массива 50


In [2]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

# В NumPy вектор и массив - одно и то же. 
# Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, 
# где один из атрибутов shape равен 1.

print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [3]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

# вычислим долю жилой площади в квартире
share_living_space = round(apartment[1]/apartment[0], 2) # запишем с двумя знаками после запятой

# Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. 
# Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:
apartment = np.delete(apartment, [0, 1])

# добавим в конец нашего массива новый признак share_living_space, 
# который сочетает в себе смысл двух старых признаков
apartment = np.append(apartment, share_living_space)
print(*apartment) # !внимание! тут поставлена * перед массивом, чтобы вывести значения в обычном формате, а не е+01

19.0 2.0 60550.0 2.0 0.53


### Задание 1.2.1
Введите значение получившегося нового признака share_living_space. Используйте код и ссылки на документацию из описания квартиры.

In [4]:
temp = apartment[4]
temp

0.53

### Задание 1.2.2
Укажите размерность конечного массива apartment после преобразования (ввода новой переменной и удаления старых).

In [5]:
temp = len(apartment)
temp

5

### Задание 1.2.3
Пусть дан вектор в python вида t = np.array(\[12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13\]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно.
Выберите неверное утверждение:

Ответ: Неверный пункт - t2 = 17 градусов C - средняя температура воздуха в феврале 

### 1.3. Базовые операции над векторами

### Задание 1.3.2
Найдите сумму и разность вектров x=(\[5,2\]) и y=(\[-5,-11\])

In [6]:
x = np.array([5, 2])
y = np.array([-5, -11])
temp = x+y
temp2 = x-y

print(temp)
print(temp2)

[ 0 -9]
[10 13]


### Задание 1.3.3  
Доходы Алексея за три месяца составили 120, 150 и 90 тысяч рублей, его жены: 130, 130 и 130 тысяч рублей, а тёщи: 2, 3 и 2.5 тысячи евро.  
1. Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.  
2. Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.

In [7]:
husband_RUB = np.array([120, 150, 90])
wife_RUB = np.array([130, 130, 130])
mother_in_law_EUR = np.array([2, 3, 2.5])

temp = mother_in_law_EUR*72
temp2 = husband_RUB + wife_RUB + temp

print(temp)
print(temp2)

[144. 216. 180.]
[394. 496. 400.]


### Инструкция по формулам в Markdown
---
$ L(x_{1}, x_{2}, ..., x_{n}  
 \mu) =  \mu * (1-\mu) $

$log (\ L(x_{1}, x_{2}, ..., x_{n}| \mu)) = h * log(\mu) + (m-h) * log(1-\mu) $

$\frac{\partial  log(\ L(x_{1}, x_{2}, ..., x_{n}| \mu)}{\partial(\mu)}  = \frac{h}{\  u} + \frac{h-m}{1-\mu} $

#### We set this to zero to find the value that  aximizes the likelihood 

$\frac{h}{\mu}    \frac{h-m}{1-\  u} = 0 $

$h = m * \mu $

$\mu = \frac{h}{m} $

### 1.4. Линейная комбинация векторов

### Задание 1.4.1
Найдите линейную комбинацию векторов  
$x = {4 \choose 5} , y = {2 \choose 1}, u = {0 \choose 1}$  
с коэффициентами 2, -3, 5

In [8]:
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])
a, b, c = 2, -3, 5

temp = a*x + b*y + c*u
temp

array([7, 7])

### Задание 1.4.2  
Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.  
На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.  
Найдите вектор прибыли Вовочки за эти 4 недели.

In [9]:
weekProduction = np.array([3,4,5,9])
weekSales = np.array([1,5,3,6])
unitProductionСost = 200
unitSalesPrice = 400
result = unitSalesPrice - unitProductionСost

temp = unitSalesPrice*weekSales - unitProductionСost*weekProduction
temp


array([-200, 1200,  200,  600])

### Задание 1.4.3
Какие системы векторов являются линейно зависимыми?  
***Ответ:***  
$x = {-1 \choose -2} , y = {1 \choose 2}$    
$x = {-3 \choose -2} , y = {1 \choose 1}, u = {4 \choose 3}$  

### 1.5. Скалярное произведение векторов

### Задание 1.5.1
Результатом скалярного произведения векторов является  

***Ответ:*** Число  

### Задание 1.5.2
Найдите скалярное произведение векторов  
```python
x = np.array([4,5,-1])
y = np.array([2,0,1])
```

In [10]:
import numpy as np

x = np.array([4,5,-1])
y = np.array([2,0,1])

temp = np.dot(x,y)
temp

7

### Задание 1.5.3
Выберите верные утверждения о длине вектора  
***Ответ:*** 
- Длина вектора равна нулю, только если сам вектор нулевой  
- Квадрат длины вектора равен его скалярному произведению с самим собой  

### Задание 1.5.4
Вычислите длину вектора x = np.array([4,6,1]). Ответ округлите до сотых.

In [11]:
x = np.array([4,6,1])

temp = np.dot(x,x)**0.5
round(temp, 2)

7.28

### Задание 1.5.5
Какие пары векторов являются ортогональными? Ответ: 2 и 4

In [12]:
import numpy as np

x = np.array([4,2,-1])
y = np.array([2,0,1])

temp = np.dot(x,y)
temp

7

In [13]:
import numpy as np

x = np.array([4,5,-1])
y = np.array([0,0,0])

temp = np.dot(x,y)
temp

0

In [14]:
x = np.array([4,-1])
y = np.array([-1,4])

temp = np.dot(x,y)
temp

-8

In [15]:
x = np.array([4,-1])
y = np.array([1,4])

temp = np.dot(x,y)
temp

0

### 1.6. Векторы. Практическая задача

### Задание 1.6.1
Прогноз оптимальной арендной платы для новой квартиры не изменился после добавления информации о нежилой площади, так как:  
***Ответ:*** Новый фактор линейно зависим со старыми

### Задание 1.6.2
Комментарий к заданию 1.6.2. Длина вектора - число, которое ставится в соответствие каждому элементу векторного пространства. Оно у разных векторов может совпадать или различаться. При этом векторы имеют равное количество координат, потому что они из одного пространства определенной размерности. И операция сложения, заданная на пространстве, предполагает, что слагаемые имеют равное количество координат. Но они могут иметь как одну длину, так и различную.  
Выберите верные утверждения:  
***Ответ:***  
- Угол между ортогональными векторами составляет 90 градусов
- если a||b и b||c, то a||c

### 1.7. Практика. Векторы

In [16]:
import numpy as np
# как создать вектор?

In [17]:
# как одномерный массив numpy
a=np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [18]:
np.array([1,2,3], dtype='float')

array([1., 2., 3.])

In [19]:
# преобразовать из списка (list)
x=[1,2,3]
x_arr=np.array(x)
print(x, type(x))
print(x_arr, type(x_arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [20]:
# нулевой вектор
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [21]:
# вектор из единиц
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
# массив чисел по порядку
np.arange(10,50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
# случайный вектор
np.random.randint(-4, 2, 10) # dim=10, случаные целые числа от -4 до 2

array([-2, -3, -1,  1,  0, -1, -1,  0, -3, -2])

In [24]:
# преобразовать из Pandas Series
import pandas as pd
data = [65, 70, 120, 35]
s = pd.Series(data)
print('Series:\n',s)

Series:
 0     65
1     70
2    120
3     35
dtype: int64


In [25]:
x = s.values # возвращает значения s
print('vector:\n',x)
print('type of x:',type(x))

vector:
 [ 65  70 120  35]
type of x: <class 'numpy.ndarray'>


In [26]:
# преобразовать из Pandas DataFrame
d = {'$$': [65, 70, 120, 35], '2.Area': [50, 52, 80, 33],'3.Rooms':[3,2,1,1], 
     '4.Floor':[5,12,10,3], '5.Demo':[8,4,5,10]}
df = pd.DataFrame(d)
print('Data Frame:\n',df)

Data Frame:
     $$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10


In [27]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8]
 [ 70  52   2  12   4]
 [120  80   1  10   5]
 [ 35  33   1   3  10]]


In [28]:
x=A[1] # вторая строка матрицы А
print('Second apartment vector:\n',x)
print('type of x:',type(x))

Second apartment vector:
 [70 52  2 12  4]
type of x: <class 'numpy.ndarray'>


In [29]:
y=A[:,0] # первый столбец матрицы А
print('$$ vector:\n',y)

$$ vector:
 [ 65  70 120  35]


In [30]:
# индексация векторов - поиск нужной координаты
print('$$ of 3 apartment:',y[2]) # третья координата

$$ of 3 apartment: 120


In [31]:
# размерность вектора
print('Number of apartments = dim(y):', len(y))

Number of apartments = dim(y): 4


In [32]:
# сумма векторов и умножение на число
a=np.array([1,2,3])
b=np.array([6,7,8])
print('a+b:',a+b)
print('2a:',2*a)

a+b: [ 7  9 11]
2a: [2 4 6]


In [33]:
# сумма списков и умножение на число не является векторной операцией!
a_list=[1,2,3]
b_list=[6,7,8]
print('a+b:',a_list+b_list)
print('2a:',2*a_list)

a+b: [1, 2, 3, 6, 7, 8]
2a: [1, 2, 3, 1, 2, 3]


In [34]:
# линейная комбинация с коэффициентами 2, 2, 3
a=np.array([1,2,3])
b=np.array([6,7,8])
c=np.array([1,0,1])

d=2*a+2*b+3*c
print('linear combination:',d)

linear combination: [17 18 25]


In [35]:
# скалярное произведение

s=np.dot(a,b)
print('scalar product:',s)

# покоординатное умножение
print('coordinate product:',a*b)

scalar product: 44
coordinate product: [ 6 14 24]


In [36]:
# скалярное произведение - еще один способ
s1=a@b
print('scalar product:',s1)

scalar product: 44


In [37]:
# длина вектора
l=np.linalg.norm(a)
print('length of a:',l)

length of a: 3.7416573867739413


In [38]:
# нормировка
a_norm=a/np.linalg.norm(a)
print('a_norm:',a_norm)
print('length of a_norm:',np.linalg.norm(a_norm))

a_norm: [0.26726124 0.53452248 0.80178373]
length of a_norm: 1.0


In [39]:
#пропорциональность и ортогональность
a=np.array([1,2,1])
b=a*2
c=np.array([-1,1,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 2 1]
b: [2 4 2]
c: [-1  1 -1]


In [40]:
#пропорциональность и ортогональность
print("(a,b):",np.dot(a,b))
print("(a,c):",np.dot(a,c))
print("(b,c):",np.dot(b,c))

(a,b): 12
(a,c): 0
(b,c): 0


In [41]:
# попарная ортогональность - да
a=np.array([1,0,1])
b=np.array([0,1,0])
c=np.array([1,0,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 0 1]
b: [0 1 0]
c: [ 1  0 -1]


In [42]:
# попарная ортогональность - да
print('(a,b):',np.dot(a,b))
print('(b,c):',np.dot(b,c))
print('(a,c):',np.dot(a,c))

(a,b): 0
(b,c): 0
(a,c): 0


In [43]:
# попарная ортогональность - нет
c1=np.array([1,0,4])
print('a:',a)
print('b:',b)
print('с1:',c1)

a: [1 0 1]
b: [0 1 0]
с1: [1 0 4]


In [44]:
# попарная ортогональность - нет
print('(a,b):',a@b)
print('(b,c1):',b@c1)
print('(a,c1):',a@c1)

(a,b): 0
(b,c1): 0
(a,c1): 5


### Задача 1
Условие
В Hut_Paradise_DF представлен фрагмент базы данных агенства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [45]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

### Задание 1.7.1
Найдите вектор параметров квартиры номер 5

In [46]:
df = pd.DataFrame(Hut_Paradise_DF)
print('Data Frame:\n',df)

Data Frame:
    1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40


In [47]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8  37]
 [ 70  52   2  12   4  40]
 [120  80   1  10   5  65]
 [ 35  33   1   3  10  20]
 [ 40  33   1   6  20  16]
 [ 50  44   2  13  12  35]
 [100  80   4   8   5  60]
 [ 90  65   3  21   1  50]
 [ 85  65   2   5  10  40]]


In [48]:
temp = x=A[4] # пятая строка матрицы А
temp

array([40, 33,  1,  6, 20, 16])

### Задание 1.7.2
Найдите вектор этажей всех квартир:

In [49]:
temp = A[:,3] # четвертый столбец матрицы А
# Выведем красиво сразу для копирования в ответ: без скобок и с запятой без пробелов
print(*temp, sep=',')

5,12,10,3,6,13,8,21,5


### Задание 1.7.3
На каком этаже расположена квартира номер 3?

In [50]:
temp = A[:,3]
temp2 = temp[2]
temp2

10

### Задание 1.7.4
Найдите количество квартир

In [51]:
temp = len(A)
temp

9

### Задание 1.7.4
Вычислите вектор нежилой площади:

In [52]:
y2 = A[:,1] # второй столбец матрицы А - Area
y6 = A[:,5] # шестой столбец матрицы А - Liv.Area
temp = y2-y6
print(*temp, sep=',')

13,12,15,13,17,9,20,15,25


### Задание 1.7.6
Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны

In [53]:
print(A[:,0]*0.4)

[26. 28. 48. 14. 16. 20. 40. 36. 34.]


### Задание 1.7.7
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [54]:
x = np.array([10,20,30,15,5,40,20,8,20])
y_demo = A[:,4] # пятый столбец матрицы А - Demo two weeks

temp = np.dot(x, y_demo)
temp

1348

In [55]:
# Второй вариант
time = np.array([10,20,30,15,5,40,20,8,20])

print(Hut_Paradise_DF.iloc[:,4]@time)

1348


### Задача 2. 
***Условие:***
Даны три вектора:  
u=np.array(\[3,0,1,1,1\])  
v=np.array(\[0,1,0,2,-2\])  
w=np.array(\[1,-4,-1,0,-2\])  
Проверьте, являются ли векторы попарно ортогональными.  

### Задание 1.7.8  
Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [56]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
a, b = 2, -3

temp= 2*v +(- 3*w)
temp

array([-3, 14,  3,  4,  2])

In [57]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
a, b = 2, -3

temp= 2*v - 3*w # Второй вариант записи
print(*temp, sep=',')  # И запишем ответ красиво

-3,14,3,4,2


### Задание 1.7.9
Будет ли эта комбинация ортогональна вектору u?

In [58]:
temp2 = np.dot(u,temp)  # скалярное произведение
temp2

0

Ответ: Да

### Задание 1.7.10
Нормируйте векторы u,v,w. 
В ответ запишите, округлив до трёх знаков после точки:  
1. третью координату u_norm   
2. четвертую координату v_norm  
3. первую координату w_norm

In [59]:
u_norm = (u/np.linalg.norm(u))[2]
v_norm = (v/np.linalg.norm(v))[3]
w_norm = (w/np.linalg.norm(w))[0]

print(round(u_norm, 3))
print(round(v_norm, 3))
print(round(w_norm, 3))

0.289
0.667
0.213


### 1.8. Матрицы. Основные понятия

In [60]:
# Пример

A = np.array([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
print(f'Матрица А:')
print(A)
print(f'A.shape:= {A.shape}')
print(f'A[1,2]:= {A[1,2]}')
print(f'A[2,1]:= {A[2,1]}')
print(f'A[2,2]:= {A[2,2]}')
B = np.matrix([[1,0,0],[0,1,0],[0,0,1]])
B

Матрица А:
[[ 1 -5  3]
 [ 2  2  1]
 [ 0  3  1]
 [ 2  4 12]]
A.shape:= (4, 3)
A[1,2]:= 1
A[2,1]:= 3
A[2,2]:= 1


matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Задание 1.8.1

1. Определите размер матрицы: 3х5
2. Элемент матрицы a24 = 5
3. Матрица A является Прямоугольной "длинной"
4. Сколько элементов на главной диагонали матрицы А? Ответ 3


### Задание 1.8.2

Матрица М является: квадратной, диагональной, симметричной

### Задание 1.8.3

Матрица является: единичной матрицей

### 1.9. Базовые действия над матрицами

In [61]:
A = np.array([[1,5,4],[1,0,1]])
A

array([[1, 5, 4],
       [1, 0, 1]])

In [62]:
A.T

array([[1, 1],
       [5, 0],
       [4, 1]])

### Задание 1.9.1

Найдите сумму матриц

In [63]:
A = np.array([[1,1],[5,7]])
B = np.array([[6,1],[-5,5]])
temp = A+B
temp

array([[ 7,  2],
       [ 0, 12]])

### Задание 1.9.2

Вынесите множитель из матрицы


In [64]:
A = np.array([[3,9],[6,27]])
B = A/3
B

array([[1., 3.],
       [2., 9.]])

### Задание 1.9.3

Транспонируйте матрицу R

In [65]:
R = np.array([[1,5,4],[0,1,0]])
R.T

array([[1, 0],
       [5, 1],
       [4, 0]])

### Задание 1.9.3

Выберите верные утверждения:

1. Диагональная матрица является инвариантом транспонирования
2. Если вычесть из квадратной матрицы единичную, поменяется только главная диагональ
3. Все столбцы диагональной матрицы ортогональны друг другу

### 1.10. Практика. Базовые действия над матрицами

In [66]:
import numpy as np

In [67]:
# как создать матрицу?

In [68]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [69]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [70]:
# размер матрицы
np.shape(A)

(4, 3)

In [71]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [72]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [73]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


In [74]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


In [75]:
# создание специальных матриц

In [76]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [80]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [81]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [82]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [83]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [84]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [85]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [86]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [87]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [88]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [89]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [90]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [91]:
x_col.T

array([[1, 2, 3]])

In [92]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


### Задача 1.10.1 
***Условие:*** Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы NumPy

In [93]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

### Задание 1.10.1
Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы:  
В ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую (без пробела):

In [94]:
Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T

print(Inc[0,0], Inc[1,1], Inc[2,2],sep=',') 
# Сделаем красивый вывод для ответа (через запятую без пробелов) с помощью sep=','

100,200,100


### Задание 1.10.2
Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.  
В ответ запишите диагональные элементы (по побочной диагонали) этой матрицы через запятую (без пробела)

In [95]:
Cons=np.array([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption]).T

print(Cons[0,2], Cons[1,1], Cons[2,0],sep=',') 
# Сделаем красивый вывод для ответа (через запятую без пробелов) с помощью sep=','

100,80,60


### Задание 1.10.3
Доходы представлены до уплаты налогов. Налоговая ставка — 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.  
В ответ запишите элементы из 1 строки этой матрицы через запятую (без пробелов)

In [96]:
Inc_Tax=Inc*(1-0.13)

print(*Inc_Tax[0],sep=',')
# Сделаем красивый вывод для ответа (без скобок - *, через запятую без пробелов - с помощью sep=',')

87.0,130.5,78.3


### Задание 1.10.4  
Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами).  
В ответ запишите элементы из 3 строки этой матрицы через запятую (без пробела)

In [97]:
Р=Inc_Tax-Cons

print(*Р[2],sep=',')
# Сделаем вывод без скобок - *, через запятую без пробелов - с помощью sep=','

61.8,-26.900000000000006,-53.0


### 1.11. Умножение матриц

### Задание 1.11.1
1. Когда можно найти произведение двух матриц A • B?  

***Ответ:***
- $A = {1\ 2\ 1\choose 4 \ 4\ 4} , B = {1\ 0\ 6\choose 0 \ 1\ 0}$  
- А размера 8 на 3 и B размера 3 на 5

2. Для корректного умножения матриц должны совпадать:  

***Ответ:***
- Число столбцов левой матрицы и число строк правой верно

### Задание 1.11.2
В произведении C = AB матриц  
1. c~1~2  
2. с~3~4

In [98]:
A = np.array( [ [1,-1, 2, 4, 0] , [8, 2, 0, 5, 3] , [0, 1, 2, 1, 2] ] )
B = np.array( [ [1, 0, 1, 0] , [0, 0, 2, -1] , [1, 0, 1, 1], [0, 1, 1, 1], [1, 1, 0, -1] ] )
C = np.dot(A,B)
print(C)
temp1 = C[0,1]
temp2 = C[2,3]

task = '1.11.2'

print(f"Ответ к заданию {task}")
print(f"c 12 {temp1}")
print(f"c 34 {temp2}")

[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]
Ответ к заданию 1.11.2
c 12 4
c 34 0


### Задание 1.11.3

Матрица какого размера получится, если умножить

In [105]:
A = np.array( [ [1, 2, 1] , [4, 4, 4] ] )
B = np.array( [ [1, 0, 6, 1] , [0, 1, 0, 1] , [6, 0, 1, 1] ] )
C = np.dot(A,B)
print(C.shape)
print(C)

(2, 4)
[[ 7  2  7  4]
 [28  4 28 12]]


### Задание 1.11.3

Найдите тензорное произведение векторов

In [110]:
a = np.array( [ 1,3 ] )
b = np.array( [ -3,1 ] )
c = np.outer(a,b) # outer для вычисления тензорного произведения
c

array([[-3,  1],
       [-9,  3]])

### 1.12. Умножение на специальные матрицы

### Задание 1.12.1
АВ = ВА, если

Хотя бы одна из матриц шаровая  
Обе матрицы диагональные

### Задание 1.12.2
Найдите АВ и ВА

In [111]:
A = np.array([[2, 0], [0, 3]])
B = np.array([[1, 1], [4, 5]])
print("AB")
print(с)
print("BA")
print(np.dot(B,A))

AB
[[ 2  2]
 [12 15]]
BA
[[ 2  3]
 [ 8 15]]


### Задание 1.13.1
Подберите элемент a22, чтобы матрицы A и B были делителями нуля

In [116]:
A = np.array([[2, -1], [-6, 3]])
B = np.array([[2, 5], [4, 10]])
np.dot(A,B)

array([[0, 0],
       [0, 0]])

### Задание 1.14.1
Выберите утверждение(-я), которое(-ые) всегда верно(-ы), если матрицы можно умножить в данном порядке:

Ответ: только второй пункт всегда верный

In [124]:
# Проверка версий
# п.1
A = np.array([[2, -1], [-6, 1]])
B = np.array([[2, 5], [4, 10]])
C = A*B
C


array([[  4,  -5],
       [-24,  10]])

In [125]:
A = np.array([[2, -1], [-6, 1]])
B = np.array([[2, 5], [4, 10]])
C = (A*B).T
C

array([[  4, -24],
       [ -5,  10]])

In [126]:
A = np.array([[2, -1], [-6, 1]])
B = np.array([[2, 5], [4, 10]])
C = A.T*B.T
C

array([[  4, -24],
       [ -5,  10]])

A.T * B.T не равно (A * B).T

In [132]:
# Проверка версий
# п.2
A = np.array([[2, 3, 3], [-3, 5, -2], [-1, -2, 1]])
B = np.array([[2, 3, -1], [-3, 5, -2], [3, -2, 1]])
C = (A*B).T
C

array([[ 4,  9, -3],
       [ 9, 25,  4],
       [-3,  4,  1]])

In [133]:
A = np.array([[2, 3, 3], [-3, 5, -2], [-1, -2, 1]])
B = np.array([[2, 3, -1], [-3, 5, -2], [3, -2, 1]])
C = B*A
C

array([[ 4,  9, -3],
       [ 9, 25,  4],
       [-3,  4,  1]])

In [138]:
A = np.array([[2, 3, 3], [-3, 5, -2], [-1, -2, 1]])
B = np.array([[2, -1, 4], [-1, 3, 15], [4, 15, 4]])
C = (A*B).T
C

array([[  4,   3,  -4],
       [ -3,  15, -30],
       [ 12, -30,   4]])

In [137]:
A = np.array([[2, 3, 3], [-3, 5, -2], [-1, -2, 1]])
B = np.array([[2, -1, 4], [-1, 3, 15], [4, 15, 4]])
C = B * A
C

array([[  4,  -3,  12],
       [  3,  15, -30],
       [ -4, -30,   4]])

Делаем вывод: если А и В симметричные матрицы, то АВ.T = BA только если эти матрицы одинаковые по форме

In [129]:
# Проверка версий
# п.3
A = np.array([[2, -1], [-6, 1]])
C = A.T*A
C

array([[4, 6],
       [6, 1]])

In [128]:
A = np.array([[2, -1], [-6, 1]])
C = A*A
C.T

array([[ 4, 36],
       [ 1,  1]])

A.T * A не равно A * A.T

### Задание 1.14.2  
Найдите матрицу Грама G системы векторов:  
$a = {1\choose 1} , b = {2\choose -1}, c = {1\choose 2}$

In [117]:
X = np.array( [ [1,2,1] , [1,-1,2] ] )
np.dot(X.T,X)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

### Задание 1.14.3
Укажите все верные утверждения^

На главной диагонали матрицы Грама G стоят квадраты длин векторов a, b, c
Нули в 3 строке и 3 столбце матрицы G означают, что векторы b и c ортогональны
Столбцы матрицы G линейно зависимы

### 1.15 Практика. Умножение матриц

In [139]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [140]:
A

array([[10,  6,  8],
       [11, 10,  8],
       [11,  9, 10]])

In [141]:
B

array([[-1,  2,  0],
       [ 0,  0, -2],
       [-2,  2,  2]])

In [142]:
# Поэлементное умножение
A*B

array([[-10,  12,   0],
       [  0,   0, -16],
       [-22,  18,  20]])

In [143]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-26  36   4]
 [-27  38  -4]
 [-31  42   2]]


In [144]:
# Матричное умножение (скалярное произведение)
np.dot(A,B)

array([[-26,  36,   4],
       [-27,  38,  -4],
       [-31,  42,   2]])

In [146]:
# Матричное умножение (скалярное произведение)
A@B

array([[-26,  36,   4],
       [-27,  38,  -4],
       [-31,  42,   2]])

In [147]:
# Порядок умножения AB != BA
B@A

array([[ 12,  14,   8],
       [-22, -18, -20],
       [ 24,  26,  20]])

In [148]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 8  6  9  5  6]
 [10 11 10  7  7]
 [ 9  8  9  7  6]]
B:
 [[ 0  0]
 [ 0  0]
 [ 3  0]
 [ 2 -2]
 [-1 -1]]


In [149]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[ 31, -16],
       [ 37, -21],
       [ 35, -20]])

In [150]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [151]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [152]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-4 -1  1 -1]
 [ 2  3  0  3]
 [-3 -3 -1  1]
 [-3  0 -1 -3]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-4 -2  0  1]
 [ 2  6  0 -3]
 [-3 -6  0 -1]
 [-3  0  0  3]]
DA:
 [[-4 -1  1 -1]
 [ 4  6  0  6]
 [ 0  0  0  0]
 [ 3  0  1  3]]


In [153]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [154]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [155]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [156]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [157]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [158]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [159]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

### Задача 1.15.1. 
Условие
```python 
A=np.array([[5, -1, 3, 1, 2],[-2, 8, 5, -1, 1]])
x=np.array([1, 2, 3, 4, 5])
```
Найдите произведение матрицы A и вектора x в том порядке, в котором их можно умножить.

In [160]:
A=np.array( [ [5,-1,3,1,2] , [-2,8,5,-1,1] ] )
x=np.array( [1,2,3,4,5] )
print(A@x)

[26 30]


### Задание 1.15.2 
***Условие:*** Даны две матрицы:
```python
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
```
Найдите произведение матриц A и B в том порядке, в котором их можно умножить.
В ответ запишите элемент из 1 строки и 4 столбца

In [161]:
A=np.array([[1, 9, 8, 5], [3, 6, 3, 2], [3, 3, 3, 3], [0, 2, 5, 9], [4, 4, 1, 2]])
B=np.array([[1, -1, 0, 1, 1], [-2, 0, 2, -1, 1]])
C = np.dot(B,A)

temp= C[0,3]
temp

14

In [164]:
# Второй вариант записи скалярного произведения
A=np.array([[1, 9, 8, 5], [3, 6, 3, 2], [3, 3, 3, 3], [0, 2, 5, 9], [4, 4, 1, 2]])
B=np.array([[1, -1, 0, 1, 1], [-2, 0, 2, -1, 1]])
C = B@A
C[0,3]


14

### Задание 1.15.3. 
***Условие:*** Дана система векторов:
```python
x = np.array([1,2,1,0,4])  
y = np.array([2,1,-1,1,0])  
z = np.array([-1,1,-1,0,0])  
```
Найдите матрицу Грама системы векторов x, y, z  
Введите все элементы этой матрицы через запятую (без пробела), перечисляя построчно:

In [165]:
x=np.array([1,2,1,0,4])
y=np.array([2,1,-1,1,0])
z=np.array([-1,1,-1,0,0])
A = np.array([x,y,z])

A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

### Задание 1.15.4. 
В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.  
В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.  
В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.  
Найдите вектор выручки Бориса

In [166]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [168]:
Count_DF.values[1]*Price_DF.values[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

### Задание 1.15.5. 
Найдите вектор прибыли салона по стилистам.  
Если за каждую услугу стилисты платят определенную комиссию салону.  
Вектор комиссий com=\[0.2, 0.2, 0.3, 0.1, 0.1\]  
Введите координаты вектора через запятую (без пробела):

In [178]:
C = Count_DF.values
P = Price_DF.values
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

profit = (P*C)@(com)
print(profit)


[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


### Задание 1.15.6. 
Найдите вектор прибыли стилистов

In [179]:
styl_inc = (P*C)@(np.ones(5)-com)

print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


### Задание 1.16.1

In [186]:
D = np.array([[a,b],[c,d]])
a = 1
b = 2
c = 2 
d = 4

print(D)

print(a*d - b*c)

print('Разница = 0, обратная матрица не существует')

[[1 2]
 [2 4]]
0
Разница = 0, обратная матрица не существует


### Задание 1.16.2
Какое число должно стоять на месте знака вопроса в равенстве

Ответ: -2


### Задания 1.16.3 - 1.16.4


In [189]:
B = np.array([[1,2],[2,5]])
print('матрица В')
print(B)


print('матрица обратная к B')
print(np.linalg.inv(B))
print('Обратная матрица Целочисленна и Симметрична')

матрица В
[[1 2]
 [2 5]]
матрица обратная к B
[[ 5. -2.]
 [-2.  1.]]
Обратная матрица Целочисленна и Симметрична


### Задание 1.16.5


In [196]:
A = np.array([[2,0,0], [0,4,0], [0,0,5]])
B = np.array([[1/2,0,0], [0,1/4,0], [0,0,1/5]])
np.dot(A,B)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.17. Определитель матрицы

### Задание 1.17.1
Найдите det(A), det(B), det(A+B), если
```python
A = np.array([[1,2],[1,1]])
B = np.array([[5,-2],[-1,4]])
```

In [203]:
A = np.array([[1,2],[1,1]])
B = np.array([[5,-2],[-1,4]])

temp = np.linalg.det(A)
temp2 = np.linalg.det(B)
temp3 = np.linalg.det(A+B)

print(round(temp, 0))
print(round(temp2, 0))
print(round(temp3, 0))

-1.0
18.0
30.0


### Задание 1.17.2
Какое утверждение неверно?

Ответ: det(A + B) = det(A) + det(B)

### Задание 1.17.3

In [215]:
A = np.array([[2,0,0],[0,1,0],[0,0,4]])
result = np.linalg.det(A)
print(round(result,3))


8.0


In [217]:
A_1 = 1/result
print(round(A_1, 3))

0.125


### Задание 1.17.4

Квадратная матрица обязательно обратима, если:
 - Её столбцы линейно независимы
 - Её определитель не равен нулю


### 1.18. Линейная (не)зависимость ч.1

### 1.19. Линейная (не)зависимость ч.2

### Задание 1.19.1

Пропорциональные векторы называются коллинеарными. Найдите неверное утверждение:
- Коллинеарные векторы всегда линейно зависимы
- Коллинеарные векторы всегда ортогональны
- Нулевой вектор коллинеарен любому вектору

Ответ: Коллинеарные векторы всегда ортогональны

### Задание 1.19.2

Выберите верное утрверждение для векторов: 
- Линейно независимы в целом
- Попарно линейно независимы (то есть каждая пара линейно независима)

In [218]:
import numpy as np

a = ([4,0])
b = ([1,1])
c = ([6,4])
A = np.array([a,b,c])

np.linalg.matrix_rank(A)

2

Ранг = 2, а векторов 3. Значит, каждая пара линейно независима

### Задание 1.19.3
Если в квадратной матрице A есть нулевой столбец, то

In [225]:
# Посмотрим на примере
B = np.array([[0,2], [0,5]])
B

array([[0, 2],
       [0, 5]])

In [224]:
np.linalg.det(B)

0.0

Ответ:

- Столбцы A линейно зависимы
- Определитель A равен нулю
- A не обратима

### Задание 1.19.4
Выберите верные утверждения для векторов

In [227]:
a = ([4,1,0])
b = ([-1,4,0])
c = ([0,0,1])

np.dot(a,b)

0

In [228]:
np.dot(b,c)

0

In [229]:
a = ([4,1,0])
b = ([-1,4,0])
c = ([0,0,1])
A = np.array([a,b,c])

np.linalg.matrix_rank(A)

3

Ответ:
- Попарно ортогональны (то есть каждая пара ортогональна)
- Попарно линейно независимы (то есть каждая пара неколлинеарна)
- Линейно независимы в целом

### Задание 1.19.5
Найдите ранги матриц А и В

In [230]:
A = np.array([[1,0,3,5],
             [0,4,5,5],
             [0,0,0,0],
             [0,0,0,0]])
B = np.array([[1,0,3,5],
             [0,4,5,5],
             [0,0,0,4],
             [0,0,0,0]])
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

2
3


### 1.20. Практика. Обратная матрица, ранг, определитель

In [231]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [232]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [233]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [234]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[ 1.00000000e+00 -4.44089210e-16 -1.11022302e-16]
 [ 4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 4.44089210e-16  8.88178420e-16  1.00000000e+00]] 1
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
check OK


In [235]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [236]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [237]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

LinAlgError: Singular matrix

In [238]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [239]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [240]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

A3 inversed:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [241]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

A3 @ A3 inversed = E check:
 [[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]
check failed


In [242]:
print('det(A1)):\n',np.linalg.det(A1))

det(A1)):
 -3.000000000000001


In [243]:
print('det(A2)):\n',np.linalg.det(A2))

det(A2)):
 0.0


In [244]:
print('det(A3)):\n',np.linalg.det(A3))

det(A3)):
 -9.51619735392994e-16


In [245]:
# обратная матрица - нестойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

A4:
 [[1.      2.      3.     ]
 [4.      5.      6.     ]
 [1.      2.      3.00005]]
rk(A4):
 3
det(A4):
 -0.00014999999999965044
A4 inverse:
 [[-2.00016667e+04  6.66666667e-01  2.00000000e+04]
 [ 4.00013333e+04 -3.33333333e-01 -4.00000000e+04]
 [-2.00000000e+04  0.00000000e+00  2.00000000e+04]]


In [246]:
# обратная матрица - нестойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

A5:
 [[1.         2.         3.        ]
 [4.         5.         6.        ]
 [1.         2.         3.00000005]]
rk(A5):
 3
det(A5):
 -1.5000000042064706e-07
A5 inverse:
 [[-2.00000016e+07  6.66666667e-01  1.99999999e+07]
 [ 4.00000012e+07 -3.33333333e-01 -3.99999999e+07]
 [-1.99999999e+07  0.00000000e+00  1.99999999e+07]]


In [247]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

A:
 [[1 1]
 [2 1]
 [1 1]]
Матрица Грама:
 [[6 4]
 [4 3]]


In [248]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

Ранг матрицы Грама:
 2


In [249]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

Определитель матрицы Грама:
 2.0000000000000004


In [250]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

Обратная к матрице Грама:
 [[ 1.5 -2. ]
 [-2.   3. ]]


### Задание 1.20.1
Найдите обратную матрицу к матрице А  
В ответ запишите элемент из 2 строки и 1 столбца

In [251]:
A = np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])

A_inv = np.linalg.inv(A)

print(A_inv[1,0])


0.375


### Задание 1.20.2
Найдите ранг системы векторов v1, v2, v3, v4

In [252]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

A = np.array([v1,v2,v3,v4]).T
np.linalg.matrix_rank(A)

4

### Задание 1.20.3
Является ли система векторов v1, v2, v3, v4 линейно зависимой?

Ответ: Нет

### Задание 1.20.4 
Найдите матрицу Грама системы векторов v1, v2, v3, v4  
В ответ запишите элемент из 1 строки и 4 столбца

In [255]:
B = A.T
Gram = B@B.T
Gram[0,3]

-35

### Задание. 1.20.5
Найдите определитель матрицы Грама системы v1, v2, v3, v4  
***Ответ округлите до целой части:***

In [256]:
result = np.linalg.det(Gram)
print(round(result,0))

3716648.0


### Задание 1.20.6
Является ли матрица Грама системы v1, v2, v3, v4 вырожденной?  
Ответ: Нет

In [259]:
# Проверим по рангу и количеству векторов
np.linalg.matrix_rank(Gram)

4

### Задание 1.20.7 
Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4  
В ответ запишите элемент из 3 строки и 1 столбца, округлив его до трёх знаков после запятой

In [261]:
result = np.linalg.inv(Gram)[2,0]
print(round(result,3))

-0.026
